In [ ]:
import numpy as np

Let's make some arrays to practice working with.

In [ ]:
arr_a = np.array([1, 2, 3, 4, 5])
arr_b = np.array([6, 7, 8, 9, 10])

# Arithmetic

## Addition
We can add these two arrays **element-wise** using the `+` operator....

In [ ]:
arr_a + arr_b

array([ 7,  9, 11, 13, 15])

... or the `np.add()` function.

In [ ]:
np.add(arr_a,arr_b)

array([ 7,  9, 11, 13, 15])

## Subtraction
Similarly, you can use the `-` operator or the `np.subtract()` function.

In [ ]:
arr_a - arr_b

array([-5, -5, -5, -5, -5])

In [ ]:
np.subtract(arr_a, arr_b)

array([-5, -5, -5, -5, -5])

## Multiplication

Element-wise multiplication can be done with the `*` operator or the `np.multiply()` function.  

_Note that there are other ways of multiplying arrays! We'll unpack this later._


In [ ]:
arr_a * arr_b

In [ ]:
np.multiply(arr_a, arr_b)

## Division
And for element-wise division, we can use the `/` operator or the `np.divide()` function.

In [ ]:
arr_a/arr_b

In [ ]:
np.divide(arr_a, arr_b)

# Logical operations
Beyond arithmetic, you can also do logical operations on arrays. For example, what if we wanted to know if any elements of our array are greater than a certain value?

In [ ]:
arr_a > 3

array([False, False, False,  True,  True])

We can also use helpful `numpy` functions like `np.any()` and `np.all()` to evaluate if _any_ or _all_ elements of an array satisfy a logical condition. Let's say we want to know if _any_ elements of `arr_a` are greater than 3.

In [ ]:
np.any(arr_a > 3)

True

Similarly, if we want to know if _all_ the elements of `arr_a` are greater than 3, we can use the `np.all()` function.

In [ ]:
np.all(arr_a > 3)

False

We can also do pairwise logical operations to compare two arrays of Boolean values. For example, if we have Boolean arrays `arr_c` and `arr_d`:

In [ ]:
arr_c = np.array([True, True, False, True])
arr_d = np.array([True, False, True, True])

Then can perform a logical AND operation between the two arrays using the `&` operator or the function `np.logical_and()`.

In [ ]:
arr_c & arr_d

array([ True, False, False,  True])