# Module 1 Challenges

In [1]:
import numpy as np

## Challenge 01
### 1.1 Create a NumPy array [1 point]

* Create a 1-dimensional NumPy array with values `1`, `2`, `3`, and `4`.
* Save it the variable `my_array`.
* Check that it has the correct value.

In [2]:
import numpy as np

my_array = np.array([1, 2, 3, 4])
print("1.1:", my_array)


1.1: [1 2 3 4]


In [3]:
# Hidden tests are within this cell

## Challenge 02
### 2.1 Create array with values as rows [1 point]

Create a **3x4** NumPy array with the values from ``list1``, ``list2``, and ``list3`` as the rows.
1. Save it to the variable ``task_two_array``.
2. Pick out the value at row `2`, column `3` and save it to the variable ``task_two_value``.
3. Pick out the third row and save it to the variable ``task_two_row``.

In [4]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
list3 = [9, 10, 11, 12]

In [5]:
# 2.1 Create array with values as rows (3x4)
task_two_array = np.array([list1, list2, list3])          # shape (3, 4)
task_two_value = task_two_array[1, 2]                     # row 2, col 3 → 0-indexed: [1,2]
task_two_row   = task_two_array[2]                        # third row
print("2.1 array:\n", task_two_array)
print("2.1 value:", task_two_value)
print("2.1 row:", task_two_row)


2.1 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2.1 value: 7
2.1 row: [ 9 10 11 12]


In [6]:
# Hidden tests are within this cell

### 2.2 Create array with values as columns [1 point]

Create a **`4`x`3`** NumPy array with the values from `list1`, `list2`, and `list3` as the columns.
1. Save it to the variable `task_three_array`.
2. Pick out the value at row `2`, column `3` and save it to the variable `task_three_value`.
3. Pick out the third row and save it to the variable `task_three_row`.

In [7]:
task_three_array = np.column_stack([list1, list2, list3]) # shape (4, 3)
task_three_value = task_three_array[1, 2]                 # row 2, col 3 → [1,2]
task_three_row   = task_three_array[2]                    # third row
print("\n2.2 array:\n", task_three_array)
print("2.2 value:", task_three_value)
print("2.2 row:", task_three_row)


2.2 array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
2.2 value: 10
2.2 row: [ 3  7 11]


In [8]:
# Hidden tests are within this cell

### 2.3 Create column array with specific value [1 point]

Create a **`3`x`5`** NumPy array with all values set to `2`. Save it to the variable `task_four_array`.

In [9]:
task_four_array = np.full((3, 5), 2)
print("\n2.3 array:\n", task_four_array)


2.3 array:
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [10]:
# Hidden tests are within this cell

### 2.4 Consider array datatypes [1 point]

Consider the following NumPy arrays.
1. Do the objects `array1` and `array2` have the same datatype? Assign your answer as a `bool` to the
   variable `mcq_1`.
2. Do the items in `array1` and `array2` have the same type? Assign your answer as a `bool` to the
   variable `mcq_2`.
3. Is the first element of `array3` an integer? Assign your answer as a `bool` to the variable `mcq_3`.

In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([1.0, 2.0, 3.0])
array3 = np.array([1, 2, 3.0])

# Q1: Do array1 and array2 have the same datatype (as Python objects)?
#     Both are np.ndarray, so True.
mcq_1 = True

# Q2: Do the items in array1 and array2 have the same type?
#     array1.dtype = int64, array2.dtype = float64 → False
mcq_2 = False

# Q3: Is the first element of array3 an integer?
#     array3 is upcasted to float64 (because of 3.0), so array3[0] is float → False
mcq_3 = False

print("\n2.4 mcq_1:", mcq_1, "mcq_2:", mcq_2, "mcq_3:", mcq_3)


2.4 mcq_1: True mcq_2: False mcq_3: False


In [12]:
# Hidden tests are within this cell

### 2.5 Extract data from an array [1 point]

Select the middle `3` rows and the middle `3` columns of `rand_array`. Save them to the variable `middle_array`.


In [13]:
np.random.seed(4242)
rand_array = np.random.randint(1, 100, size=(5, 7))

In [14]:
middle_array = rand_array[1:4, 2:5]
print("\n2.5 middle_array:\n", middle_array)


2.5 middle_array:
 [[41 73 94]
 [67 33 92]
 [20 65 49]]


In [15]:
# Hidden tests are within this cell

### 2.6 Extract data from an array [1 point]

Select the middle `3` rows (and all columns) of `rand_array`. Save them to the variable `middle_rows`.


In [16]:
middle_rows = rand_array[1:4, :]
print("2.6 middle_rows:\n", middle_rows)

2.6 middle_rows:
 [[20 94 41 73 94 43 14]
 [37 53 67 33 92 60 26]
 [48 25 20 65 49 97 43]]


In [17]:
# Hidden tests are within this cell

### 2.7 Extract data from an array [1 point]

Select the middle `3` columns (and all rows) of `rand_array`. Save them to the variable `middle_columns`.


In [18]:
middle_columns = rand_array[:, 2:5]
print("2.7 middle_columns:\n", middle_columns)

2.7 middle_columns:
 [[18 55 35]
 [41 73 94]
 [67 33 92]
 [20 65 49]
 [22  1 42]]


In [19]:
# Hidden tests are within this cell

### 2.8 Create array [1 point]

Make a **`3`x`3`** NumPy array with the values `1`, `2`, `3` on the diagonal, and 0s everywhere
else. Save it to the variable `task_nine_array`.

In [20]:
task_nine_array = np.diag([1, 2, 3])
print("\n2.8 task_nine_array:\n", task_nine_array)



2.8 task_nine_array:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [21]:
# Hidden tests are within this cell

### 2.9 Create array with nulls [1 point]

Make a **`3`x`3`** NumPy array with the values `1`, `2`, `3` on the diagonal and null values
everywhere else. Save it to the variable `task_ten_array`.

Hint: if you create the array with integer values, you will need to convert it to a `float` to add
`np.nan` values.

In [22]:
task_ten_array = np.diag([1, 2, 3]).astype(float)
task_ten_array[task_ten_array == 0] = np.nan
print("2.9 task_ten_array:\n", task_ten_array)


2.9 task_ten_array:
 [[ 1. nan nan]
 [nan  2. nan]
 [nan nan  3.]]


In [23]:
# Hidden tests are within this cell

## Challenge 03
### 3.1 Locating indices for null values [1 point]

In the first cell below we have created an array with null values in five random locations.

Find the indices of the `np.nan` values in `rand_array`. Save them to the variable `nan_indices`.
`nan_indices` should have shape `(5, 2)`. Each row should contain the row and column index of a
`np.nan` value.

In [24]:
np.random.seed(4242)
rand_array = np.random.randint(1, 100, size=(5, 7))

# Set five random values in rand_array to np.nan
indices = np.random.choice(range(rand_array.size), size=5, replace=False)
rand_array = rand_array.astype(float)
rand_array.ravel()[indices] = np.nan


In [25]:
nan_indices = np.argwhere(np.isnan(rand_array))
print("\n3.1 nan_indices:\n", nan_indices)



3.1 nan_indices:
 [[0 4]
 [1 1]
 [2 3]
 [3 6]
 [4 1]]


In [26]:
# Hidden tests are within this cell

### 3.2 Replace missing data [1 point]

Replace the missing indices in `rand_array` with the value `1000`. Save the result to the variable
`filled_array`.

In [27]:
filled_array = rand_array.copy()
filled_array[np.isnan(filled_array)] = 1000
print("3.2 filled_array:\n", filled_array)


3.2 filled_array:
 [[  47.   14.   18.   55. 1000.   81.   18.]
 [  20. 1000.   41.   73.   94.   43.   14.]
 [  37.   53.   67. 1000.   92.   60.   26.]
 [  48.   25.   20.   65.   49.   97. 1000.]
 [  21. 1000.   22.    1.   42.   63.   98.]]


In [28]:
# Hidden tests are within this cell

## Challenge 04

Consider the following **`3`x`3`** NumPy arrays named `array1` and `array2`.

In [29]:
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

array2 = np.array([[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]])

### 4.1 Sum arrays [1 point]

Add up the two arrays **element-wise** and save the result to the variable `sum_array`.


In [30]:
sum_array = array1 + array2
print("\n4.1 sum_array:\n", sum_array)


4.1 sum_array:
 [[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]


In [31]:
# Hidden tests are within this cell

### 4.2 Sum vectors [1 point]

Below is code that attempts to add up the values in two one-dimensional vectors. The result should
be `[6, 8, 10, 12]`. However, the current code __does not__ produce the correct result. Apply the
OILER framework to help you diagnose and resolve the issue.

In [32]:
array1 = [1, 2, 3, 4]
array2 = [5, 6, 7, 8]

array3 = np.array(array1) + np.array(array2)   # → [6, 8, 10, 12]
print("4.2 array3:", array3)

4.2 array3: [ 6  8 10 12]


In [33]:
# Hidden tests are within this cell